STATE_START = "start"
STATE_ASK_AMOUNT = "ask_amount"
STATE_ASK_PURPOSE = "ask_purpose"
STATE_CHECK_INCOME = "check_income"
STATE_INELIGIBLE_FINANCIAL = "ineligible_financially"
STATE_SIGN_CONFIRM = "sign_confirm"
STATE_GOODBYE = "goodbye"
STATE_TERMINATE = "terminate"

ACTION_ASK_REQUIRED = "ASK_REQUIRED"
ACTION_COACH_AND_ASK_REQUIRED = "COACH_AND_ASK_REQUIRED"
ACTION_WARN_AND_ASK_REQUIRED = "WARN_AND_ASK_REQUIRED"
ACTION_WARN_AND_REDIRECT = "WARN_AND_REDIRECT"
ACTION_BOUNDARY_AND_OFFER_RESTART = "BOUNDARY_AND_OFFER_RESTART"
ACTION_END_CONVERSATION_SAFELY = "END_CONVERSATION_SAFELY"
ACTION_OFFER_RESTART = "OFFER_RESTART"
ACTION_RESTART = "RESTART"
ACTION_REPEAT_AND_EXPLAIN = "REPEAT_AND_EXPLAIN"
ACTION_TERMINATE = "TERMINATE"

BANK_STATES_ORDER = [
    STATE_START,
    STATE_ASK_AMOUNT,
    STATE_ASK_PURPOSE,
    STATE_CHECK_INCOME,
    STATE_INELIGIBLE_FINANCIAL,
    STATE_SIGN_CONFIRM,
    STATE_GOODBYE,
    STATE_TERMINATE,
]
